name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4
      
      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: pnpm 도구 설치하기
        run: npm install -g pnpm

      - name: 라이브러리 설치하기
        run: pnpm install

      - name: 웹사이트 변환(Build)하기
        run: pnpm run build
        working-directory: ./artifacts/special-edu

      - name: 변환된 파일 업로드 준비
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./artifacts/special-edu/dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 깃허브 페이지로 배포하기
        id: deployment
        uses: actions/deploy-pages@v4